#!/usr/bin/env bash
# VPS Guardian — Cron Setup Script
#
# Installs a cron job that runs a daily security scan and a weekly report,
# both with Discord notifications.
#
# Usage (run as root on your VPS):
#   bash scripts/setup-cron.sh
#
# Options:
#   --install-dir <path>   Where guardian is installed (default: /opt/vps-guardian)
#   --config <path>        Path to guardian.yml (default: <install-dir>/guardian.yml)
#   --scan-hour <0-23>     Hour for daily scan in UTC (default: 2)
#   --report-hour <0-23>   Hour for weekly report in UTC (default: 8)
#   --report-day <0-6>     Day for weekly report, 0=Sun (default: 0)
#   --no-notify            Do not send Discord notifications
#   --uninstall            Remove the cron job

set -euo pipefail

# ---------------------------------------------------------------------------
# Defaults
# ---------------------------------------------------------------------------

INSTALL_DIR="/opt/vps-guardian"
CONFIG_PATH=""
SCAN_HOUR=2
REPORT_HOUR=8
REPORT_DAY=0
NOTIFY="--notify"
CRON_FILE="/etc/cron.d/vps-guardian"
LOG_DIR="/var/log/vps-guardian"
UNINSTALL=false

# ---------------------------------------------------------------------------
# Parse args
# ---------------------------------------------------------------------------

while [[ $# -gt 0 ]]; do
  case $1 in
    --install-dir)  INSTALL_DIR="$2";  shift 2 ;;
    --config)       CONFIG_PATH="$2";  shift 2 ;;
    --scan-hour)    SCAN_HOUR="$2";    shift 2 ;;
    --report-hour)  REPORT_HOUR="$2";  shift 2 ;;
    --report-day)   REPORT_DAY="$2";   shift 2 ;;
    --no-notify)    NOTIFY="";         shift   ;;
    --uninstall)    UNINSTALL=true;    shift   ;;
    *) echo "Unknown argument: $1"; exit 1 ;;
  esac
done

# ---------------------------------------------------------------------------
# Colours
# ---------------------------------------------------------------------------

if [ -t 1 ]; then
  GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'
  BOLD='\033[1m';     RESET='\033[0m'
else
  GREEN=''; YELLOW=''; RED=''; BOLD=''; RESET=''
fi

info()    { echo -e "${GREEN}[INFO]${RESET} $*"; }
warn()    { echo -e "${YELLOW}[WARN]${RESET} $*"; }
error()   { echo -e "${RED}[ERROR]${RESET} $*" >&2; exit 1; }
section() { echo -e "\n${BOLD}━━ $* ━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"; }

# ---------------------------------------------------------------------------
# Uninstall
# ---------------------------------------------------------------------------

if [ "$UNINSTALL" = true ]; then
  section "Removing VPS Guardian cron job"
  if [ -f "$CRON_FILE" ]; then
    rm -f "$CRON_FILE"
    info "Removed $CRON_FILE"
  else
    warn "No cron file found at $CRON_FILE — nothing to remove"
  fi
  exit 0
fi

# ---------------------------------------------------------------------------
# Checks
# ---------------------------------------------------------------------------

section "Pre-flight checks"

if [ "$EUID" -ne 0 ]; then
  error "This script must be run as root. Try: sudo bash scripts/setup-cron.sh"
fi

GUARDIAN_BIN="$INSTALL_DIR/dist/cli/index.js"
if [ ! -f "$GUARDIAN_BIN" ]; then
  error "guardian binary not found at $GUARDIAN_BIN. Run the install script first."
fi

# Resolve config path
if [ -z "$CONFIG_PATH" ]; then
  CONFIG_PATH="$INSTALL_DIR/guardian.yml"
fi

if [ ! -f "$CONFIG_PATH" ]; then
  error "Config file not found at $CONFIG_PATH. Copy guardian.example.yml and fill in your settings."
fi

info "Guardian binary: $GUARDIAN_BIN ✓"
info "Config:          $CONFIG_PATH ✓"

# Validate hours/day
if ! [[ "$SCAN_HOUR"   =~ ^([0-9]|1[0-9]|2[0-3])$ ]]; then error "Invalid --scan-hour: $SCAN_HOUR"; fi
if ! [[ "$REPORT_HOUR" =~ ^([0-9]|1[0-9]|2[0-3])$ ]]; then error "Invalid --report-hour: $REPORT_HOUR"; fi
if ! [[ "$REPORT_DAY"  =~ ^[0-6]$ ]];                   then error "Invalid --report-day: $REPORT_DAY (0=Sun, 6=Sat)"; fi

# ---------------------------------------------------------------------------
# Create log directory
# ---------------------------------------------------------------------------

section "Setting up log directory"

mkdir -p "$LOG_DIR"
info "Log directory: $LOG_DIR"

# ---------------------------------------------------------------------------
# Write cron file
# ---------------------------------------------------------------------------

section "Installing cron job"

GUARDIAN_CMD="/usr/bin/env node $GUARDIAN_BIN"
CONFIG_FLAG="--config $CONFIG_PATH"

cat > "$CRON_FILE" <<EOF
# VPS Guardian — automated security monitoring
# Generated by setup-cron.sh on $(date -u '+%Y-%m-%d %H:%M UTC')
# To remove: bash scripts/setup-cron.sh --uninstall

SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# Daily security scan (runs at ${SCAN_HOUR}:00 UTC every day)
0 ${SCAN_HOUR} * * * root ${GUARDIAN_CMD} scan ${CONFIG_FLAG} ${NOTIFY} >> ${LOG_DIR}/cron.log 2>&1

# Weekly security report (runs at ${REPORT_HOUR}:00 UTC on day ${REPORT_DAY} — 0=Sunday)
0 ${REPORT_HOUR} * * ${REPORT_DAY} root ${GUARDIAN_CMD} report ${CONFIG_FLAG} ${NOTIFY} >> ${LOG_DIR}/cron.log 2>&1
EOF

chmod 644 "$CRON_FILE"

info "Cron file written to $CRON_FILE"

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------

section "Done"

DAYS=("Sunday" "Monday" "Tuesday" "Wednesday" "Thursday" "Friday" "Saturday")
REPORT_DAY_NAME="${DAYS[$REPORT_DAY]}"

echo ""
echo -e "  ${BOLD}Daily scan:${RESET}    Every day at ${SCAN_HOUR}:00 UTC"
echo -e "  ${BOLD}Weekly report:${RESET} Every ${REPORT_DAY_NAME} at ${REPORT_HOUR}:00 UTC"
echo -e "  ${BOLD}Logs:${RESET}          ${LOG_DIR}/cron.log"
echo -e "  ${BOLD}Config:${RESET}        ${CONFIG_PATH}"
echo ""

if [ -n "$NOTIFY" ]; then
  info "Discord notifications are ENABLED"
else
  warn "Discord notifications are DISABLED (--no-notify was passed)"
fi

echo ""
info "To verify: cat $CRON_FILE"
info "To remove: bash $INSTALL_DIR/scripts/setup-cron.sh --uninstall"
echo ""
